POST http://localhost:8080/api/note/getList.php?startIdx=0&count=10
Content-Type: application/x-www-form-urlencoded

text=TestContent''!\'&author=TestUser2019-12-25-2&email=test@example.com&url=

