name: Build & Deploy

on:
  push:
    paths:
      - "**/Cargo.lock"
      - "**/*.rs"

jobs:
  build:
    name: "Build Project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            model/target
            options/target
            sar_blog/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build rust project
        uses: actions-rs/cargo@v1
        with: 
          command: build
          args: --release --target=x86_64-unknown-linux-gnu

      - name: Prepare Identity
        run: echo "${{ secrets.SSH_KEY }}" > ssh_key && chmod 400 ssh_key

      - name: Deploy binary
        run: >
          scp \
            -i ssh_key \
            -o LogLevel=ERROR \
            -o StrictHostKeyChecking=no \
            target/x86_64-unknown-linux-gnu/release/sar-blog $SSH_USER@$SSH_HOSTNAME:$WORK_DIR/bin/sar-blog
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          WORK_DIR: ${{ secrets.PROJECT_DIR }}

      - name: Restart Service
        run: >
          ssh $SSH_USER@$SSH_HOSTNAME \
            -o StrictHostKeyChecking=no \
            -o LogLevel=ERROR \
            -i ssh_key \
            "cd $WORK_DIR && \
            docker-compose down --rmi local && \
            docker-compose up -d"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          WORK_DIR: ${{ secrets.PROJECT_DIR }}

