name: Check

on: push

jobs:
  build:
    name: "Check Project"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build rust project
        uses: actions-rs/cargo@v1
        with: 
          command: check
