name: Check

on: push

jobs:
  back-end:
    name: "Check Rust Project"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
          
      - uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            model/target
            options/target
            sar_blog/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build rust project
        uses: actions-rs/cargo@v1
        with: 
          command: check


  front-end:
    name: "Build Message Board"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: cd web-root/note && npm install
      - run: cd web-root/note && npm run build
      - run: cd web-root/about && npm install
      - run: cd web-root/about && npm run build