name: Deploy Static Resources

on:
  push:
    paths-ignore:
      - "**/Cargo.lock"
      - "**/*.rs"

jobs:
  build:
    name: "Deploy Static Resources"
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
          
      - uses: actions/checkout@v2
      - name: Install rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Prepare Identity File
        run: echo "${{ secrets.SSH_KEY }}" > ssh_key && chmod 400 ssh_key

      - name: Checkout Remote
        run: >
          ssh $SSH_USER@$SSH_HOSTNAME \
            -o StrictHostKeyChecking=no \
            -o LogLevel=ERROR \
            -i ssh_key \
            "cd $WORK_DIR && \
            echo 'Checkout $GITHUB_SHA' && \
            git fetch origin $GITHUB_SHA && \
            git checkout $GITHUB_SHA && \
            git log -1 --format='%H'"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          WORK_DIR: ${{ secrets.PROJECT_DIR }}

      - name: Restart Service
        run: >
          ssh $SSH_USER@$SSH_HOSTNAME \
            -o StrictHostKeyChecking=no \
            -o LogLevel=ERROR \
            -i ssh_key \
            "cd $WORK_DIR && \
            docker-compose down --rmi local && \
            docker-compose build --no-cache && \
            docker-compose up -d"
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOSTNAME: ${{ secrets.SSH_HOSTNAME }}
          WORK_DIR: ${{ secrets.PROJECT_DIR }}

